### ISSUE TITLE
unity 5

### ISSUE THREAD

**Issue by geniuscd** [dgkanatsios/FlappyBirdClone#1]
i was just testing this small project inside unity 5, but i think the physics are messed up, the bird isnt falling...

i think the call for the rigidbofy2D is old ?

**Comment by dgkanatsios** [comment]
Interesting, just confirmed it myself. No, the rigidbody2D is correctly modified to GetComponent<Rigidbody2D> during the upgrade, there must be something else, checking as we speak.

**Comment by geniuscd** [comment]
**fix**
just untick the animator apply root motion

**Comment by dgkanatsios** [comment]
If you remove the Animator component from the bird (named Flappy on the Scene) or uncheck "Apply Root Motion", the bird should fall. Weird, since the animator controller references an animation that just modifies the sprite on the SpriteRenderer. Will look more into it.
