### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by pixele** [dgkanatsios/FlappyBirdClone#2]
Hi Dimitris,

we would like to adapt and use your Flappy Bird clone game for educational purposes. Since no licence is is available we hereby request your permission to do so.

Kind regards,

Eric Klok
Amsterdam University of Applied Science

**Comment by dgkanatsios** [comment]
Hi @pixele, thanks for reaching out. Of course, feel free to use the code for whatever purpose you wish.
Thanks,
Dimitris
